name = "GCTAndGMT"
uuid = "9a662218-b2a5-48bf-9802-3ede4e75343d"
authors = ["Kwat Medetgul-Ernar <kwat.me@icloud.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.8"
DataFrames = "0.22"
julia = "1.5"
